spring.application.name=RapidosyFuriosos
server.port=8089
server.servlet.context-path=/rapidosyfuriosos
spring.datasource.url=jdbc:mysql://localhost:3306/bdrapidosyfuriosos20262
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver